server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/logbook}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop

